# Generated by Django 3.2.12 on 2023-08-13 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0002_academin_year_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, default=datetime.datetime.now, max_length=100)),
                ('end', models.CharField(blank=True, default=datetime.datetime.now, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Academin_year',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (1, 'HOD'), (2, 'STAFF')], default=1, max_length=100),
        ),
    ]
