# Generated by Django 3.2.12 on 2023-08-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0003_auto_20230813_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Branch',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (3, 'STUDENT'), (1, 'HOD')], default=1, max_length=100),
        ),
    ]
