# Generated by Django 3.2.12 on 2023-08-13 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0004_auto_20230813_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='end',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 13), max_length=100),
        ),
        migrations.AlterField(
            model_name='academic_year',
            name='start',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 13), max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (2, 'STAFF'), (1, 'HOD')], default=1, max_length=100),
        ),
    ]
