# Generated by Django 3.2.12 on 2023-08-13 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0005_auto_20230813_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (3, 'STUDENT'), (2, 'STAFF')], default=1, max_length=100),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('studentmob', models.CharField(default='0', max_length=100)),
                ('parentmob', models.CharField(default='0', max_length=100)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('batchyearID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stuapp.academic_year')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stuapp.branch')),
            ],
        ),
    ]
