# Generated by Django 3.2.12 on 2023-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0006_auto_20230813_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batchyearID',
            new_name='acadyearID',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=100),
        ),
    ]
