# Generated by Django 3.2.12 on 2023-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_year',
            new_name='batchyear',
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='acadyearID',
            new_name='batchyearID',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (1, 'HOD'), (2, 'STAFF')], default=1, max_length=100),
        ),
    ]
