# Generated by Django 3.2.12 on 2023-08-13 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0012_auto_20230813_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='batchyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, default=datetime.datetime.now, max_length=100)),
                ('end', models.CharField(blank=True, default=datetime.datetime.now, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_staff', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='batchyearID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stuapp.batchyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stuapp.course'),
        ),
        migrations.DeleteModel(
            name='acadyear',
        ),
        migrations.DeleteModel(
            name='branch',
        ),
    ]
