# Generated by Django 3.2.12 on 2023-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0016_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='batchyear',
            new_name='Batch_Year',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=100),
        ),
    ]
