# Generated by Django 3.2.12 on 2023-08-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0020_auto_20230813_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch_Year',
            new_name='Acad_year',
        ),
        migrations.RenameModel(
            old_name='course',
            new_name='Branch',
        ),
    ]
