# Generated by Django 3.2.12 on 2023-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0023_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batch_year_id',
            new_name='acad_year_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='branch_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=100),
        ),
    ]
