# Generated by Django 3.2.12 on 2023-08-14 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0024_auto_20230813_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='course_staff',
        ),
        migrations.AlterField(
            model_name='acad_year',
            name='end',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 14), max_length=100),
        ),
        migrations.AlterField(
            model_name='acad_year',
            name='start',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 14), max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (3, 'STUDENT'), (2, 'STAFF')], default=1, max_length=100),
        ),
    ]
