# Generated by Django 3.2.12 on 2023-08-15 16:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0025_auto_20230814_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad_year',
            name='end',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 15), max_length=100),
        ),
        migrations.AlterField(
            model_name='acad_year',
            name='start',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 15), max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (3, 'STUDENT'), (1, 'HOD')], default=1, max_length=100),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
