# Generated by Django 3.2.12 on 2023-08-22 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0031_auto_20230816_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acad_year',
            name='end',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 22), max_length=100),
        ),
        migrations.AlterField(
            model_name='acad_year',
            name='start',
            field=models.CharField(blank=True, default=datetime.date(2023, 8, 22), max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (2, 'STAFF'), (1, 'HOD')], default=1, max_length=100),
        ),
    ]
